// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOb6v1y5e9DiO4P-E6azmcsPa0oxeIThg',
    appId: '1:281559842198:web:e98b8a143747363d20b1b7',
    messagingSenderId: '281559842198',
    projectId: 'coffie-shop-20a76',
    authDomain: 'coffie-shop-20a76.firebaseapp.com',
    storageBucket: 'coffie-shop-20a76.appspot.com',
    measurementId: 'G-N8P7PZBNW1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNABqUbWzVo8ra6fLfVpfAPNv7Zi1Uxls',
    appId: '1:281559842198:android:039ec10f5192957520b1b7',
    messagingSenderId: '281559842198',
    projectId: 'coffie-shop-20a76',
    storageBucket: 'coffie-shop-20a76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDINi584EwnHr9Ob53IJMwCfQvtt-iq7D8',
    appId: '1:281559842198:ios:c44cf260b41a418f20b1b7',
    messagingSenderId: '281559842198',
    projectId: 'coffie-shop-20a76',
    storageBucket: 'coffie-shop-20a76.appspot.com',
    iosBundleId: 'com.example.coffieshop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDINi584EwnHr9Ob53IJMwCfQvtt-iq7D8',
    appId: '1:281559842198:ios:04d6c6cb311d3ea720b1b7',
    messagingSenderId: '281559842198',
    projectId: 'coffie-shop-20a76',
    storageBucket: 'coffie-shop-20a76.appspot.com',
    iosBundleId: 'com.example.coffieshop.RunnerTests',
  );
}
